// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwexymyiqajnfjsgtitw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3ZXh5bXlpcWFqbmZqc2d0aXR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4NjY5NTgsImV4cCI6MjA1NDQ0Mjk1OH0.TIUZyZcBim3Gr4zT7JD4sC-X5fh_hLlqN2SHbSIh4ag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);